base_config:
  configs/base.yaml

# preprocessing
binarizer_cls: null
raw_data_dir: []
binary_data_dir: null
pe: rmvpe
pe_ckpt: pretrained/rmvpe/model.pt

# neural networks
model_cls: modules.model.midi_conform.midi_conform
midi_extractor_args:
  lay: 6
  dim: 512
  indim: 768
  outtype: 128
  use_lay_skip: false
  kernel_size: 31
  conv_drop: 0.1
  ffn_latent_drop: 0.1
  ffn_out_drop: 0.1
  attention_drop: 0.1
  attention_heads: 8
  attention_heads_dim: 64

# training
task_cls: training.MIDIExtractionTask
optimizer_args:
  optimizer_cls: torch.optim.AdamW
  lr: 0.0004
  beta1: 0.9
  beta2: 0.98
  weight_decay: 0
lr_scheduler_args:
  scheduler_cls: torch.optim.lr_scheduler.StepLR
  step_size: 50000
  gamma: 0.5

max_batch_size: 48
max_batch_frames: 80000
num_valid_plots: 10
val_check_interval: 2000
num_ckpt_keep: 5
max_updates: 320000
permanent_ckpt_start: 200000
permanent_ckpt_interval: 40000

