# preprocessing
binarizer_cls: preprocessing.MIDIExtractionBinarizer
raw_data_dir:
  - ../DiffSinger/data/junninghua_v3_part1/raw
binary_data_dir: data/some_dataset/binary
binarization_args:
  num_workers: 0
  shuffle: true
hop_size: 320
audio_sample_rate: 16000
test_prefixes:
  - 'ChiLing_001'
  - 'FengYingYue_002'
  - 'JianXin_004'
  - 'JuanZhuLian_013'
  - 'QiHuang_004'
  - 'QinShi_013'
  - 'TianXia_005'
  - 'WuJiYa_001'
  - 'YeGuangBei_013'
  - 'YuanCangTianBianLeXin_000'
units_encoder: contentvec
units_encoder_ckpt: pretrained/contentvec/checkpoint_best_legacy_500.pt
pe: rmvpe
pe_ckpt: pretrained/rmvpe/model.pt

# neural networks
units_dim: 256

# training
task_cls: training.MIDIExtractionTask
optimizer_args:
  optimizer_cls: torch.optim.AdamW
  lr: 0.0004
  beta1: 0.9
  beta2: 0.98
  weight_decay: 0
lr_scheduler_args:
  scheduler_cls: torch.optim.lr_scheduler.StepLR
  step_size: 50000
  gamma: 0.5

clip_grad_norm: 1
accumulate_grad_batches: 1
sampler_frame_count_grid: 6
ds_workers: 4
dataloader_prefetch_factor: 2

max_batch_size: 48
max_batch_frames: 80000
max_val_batch_size: 1
max_val_batch_frames: 10000
num_valid_plots: 10
log_interval: 100
num_sanity_val_steps: 1  # steps of validation at the beginning
val_check_interval: 2000
num_ckpt_keep: 5
max_updates: 320000
permanent_ckpt_start: 200000
permanent_ckpt_interval: 40000

###########
# pytorch lightning
# Read https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api for possible values
###########
pl_trainer_accelerator: 'auto'
pl_trainer_devices: 'auto'
pl_trainer_precision: '32-true'
pl_trainer_num_nodes: 1
pl_trainer_strategy: 'auto'
ddp_backend: 'nccl' # choose from 'gloo', 'nccl', 'nccl_no_p2p'
seed: 114514
